# Generated by Django 3.2.10 on 2024-08-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xeroc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='user_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
