# Generated by Django 3.2.10 on 2024-08-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xeroc_app', '0002_uploadedfile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
