# Generated by Django 3.2.10 on 2024-08-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xeroc_app', '0003_uploadedfile_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
